apiVersion: apps/v1
kind: Deployment

metadata:
  name: ar-devops-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ar-devops-backend

  template:
    metadata:
      labels:
        app: ar-devops-backend

    spec:
      containers:
        - name: backend
          image: ar-devops-backend:1.5
          imagePullPolicy: Never
          env:
            - name: PROMETHEUS_URL
              value: "http://host.docker.internal:9090"

          ports:
            - containerPort: 8000
