apiVersion: v1
kind: Service

metadata:
  name: ar-devops-backend-service

spec:
  type: NodePort

  selector:
    app: ar-devops-backend

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080